site_name: Canim Documentation
plugins:
    - mkdocs-video

theme:
    name: material
    palette:
        scheme: slate
    highlightjs: true
    hljs_languages:
        - lua
        - ts
    icon:
        repo: fontawesome/brands/github

markdown_extensions:
    - admonition
    - codehilite:
          guess_lang: false
    - toc:
          permalink: true
    - pymdownx.superfences

repo_url: https://github.com/blackshibe/canim
extra_css:
    - stylesheets/extra.css
